version: '3.8'

services:
  polycules:
    container_name: polycules
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3012:3012
    environment:
      - PORT=3012
    volumes:
      - db-data:/app/backend/db.json

volumes:
  db-data:
