version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3012:3012"
    environment:
      - PORT=3012
    volumes:
      - db-data:/app/backend/db.json
    command: npm run run

volumes:
  db-data:
