version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - db-data:/app/backend/db.json
    command: npm run run

volumes:
  db-data:
